### ISSUE TITLE
Magenta error color?!?

### ISSUE THREAD

**Issue by pazuzu72** [LIV2/GottaGoFastRAM#1]
I made this expansion for my Amiga 1000 and I must say it works perfectly without any problems. The only weird thing I noticed is that on power up, before the kickstart screen, the color is magenta (?) where it was gray before.

**Comment by LIV2** [comment]
Hi @pazuzu72 

Weird! I think maybe it's because I made a mistake that caused the buffers to enable during reset which might have been causing your magenta screen.

I've attached an updated .jed file which should correct this mistake and hopefully fix your magenta screen: [gottagofast.zip](https://github.com/LIV2/GottaGoFastRAM/files/5827831/gottagofast.zip)

I hope that fixes it!

**Comment by pazuzu72** [comment]
Thanks. I'll try it later. I will post the result of the update.

**Comment by LIV2** [comment]
@pazuzu72 Did this solve your issue?

**Comment by pazuzu72** [comment]
Unfortunately I didn't have time due to work. I hope this weekend to succeed. It will be my pleasure to post the result.

**Comment by pazuzu72** [comment]
All right. The magenta is gone !! Thanks so much :-)

**Comment by LIV2** [comment]
Awesome, glad I could help!
